---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: kube-ecr-refresher
  name: kube-ecr-refresher
  namespace: kube-ecr-refresher
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kube-ecr-refresher
  name: kube-ecr-refresher
  namespace: kube-ecr-refresher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: kube-ecr-refresher
  name: kube-ecr-refresher
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - create
      - get
      - update
  - apiGroups: [""]
    resources:
      - namespaces
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: kube-ecr-refresher
  name: kube-ecr-refresher
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: kube-ecr-refresher
    namespace: kube-ecr-refresher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-ecr-refresher