---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: kube-ecr-refresher
  name: kube-ecr-refresher
  namespace: kube-ecr-refresher
stringData:
  # TODO: Fill in as appropriate.
  AWS_ACCESS_KEY_ID: ""
  AWS_REGION: ""
  AWS_SECRET_ACCESS_KEY: ""